server:
  port: 8201

spring:
  application:
    name: service-hospital-cj
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cj?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos












