server:
  port: 8203

spring:
  application:
    name: service-user-cj
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cj?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
  redis:
    host: 127.0.0.1
    port: 6379
    password:
     jedis:
        pool:
          max-active: 8
    database: 0